version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - postgres
    restart: always

  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  postgres_data: